version: '3'

services:
  osticket_dev:
    build: .
    image: barghest84/docker-osticket:develop
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=0T1cket
      - INSTALL_SECRET=osTicket
      - LANGUAGE=pl
    volumes:
      - osticket_plugins:/data/upload/include/plugins
      - osticket_i18n:/data/upload/include/i18n
      - osticket_logs:/var/log/nginx
    links:
      - mysql:mysql
    ports:
      - "8080:80"
    restart: always

  mysql:
    image: mariadb
    environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=true
       - MYSQL_DATABASE=osticket
       - MYSQL_USER=osticket
       - MYSQL_PASSWORD=0T1cket
    volumes:
      - osticket_mysql_data:/var/lib/mysql
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  osticket_plugins:
  osticket_i18n:
  osticket_logs:
  osticket_mysql_data: